vat:
  rate: 0.20 
# UK’s sales tax (20%)

database:
  driverClass: com.mysql.jdbc.Driver
  url: jdbc:mysql://db4free.net/codingtest
  user: codingtest
  password: BZx2c4d8OW
  maxWaitForConnection: 1s
  validationQuery: "SELECT 1"
  validationQueryTimeout: 3s
  minSize: 8
  maxSize: 32
  checkConnectionWhileIdle: false
  evictionInterval: 10s
  minIdleTime: 1 minute